# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kylRxMVVMDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kylRxMVVMDemo
pod 'RxCocoa'
pod 'SnapKit'
pod 'Moya/RxSwift'
pod 'Kingfisher'

  target 'kylRxMVVMDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kylRxMVVMDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
