# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kylUIFitSizeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kylUIFitSizeDemo
  pod 'SwiftyFitsize'
  pod 'SnapKit'

  target 'kylUIFitSizeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kylUIFitSizeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
