# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kylRxBluetoothDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kylRxBluetoothDemo
   # Logging
  pod 'CocoaLumberjack/Swift'
  target 'kylRxBluetoothDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kylRxBluetoothDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
