# Uncomment the next line to define a global platform for your project

#platform :ios, '9.0'

target 'kyl_DSBrigeDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kyl_DSBrigeDemo
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher'
  pod 'HandyJSON'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Moya'
  pod 'JXPhotoBrowser'
  pod 'Kingfisher'
  pod 'BayMaxProtector'
  pod 'dsBridge'
#pod 'SwiftyFitsize'

  target 'kyl_DSBrigeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kyl_DSBrigeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'RxSwift'
      target.build_configurations.each do |config|
        if config.name == 'Debug'
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
        end
      end
    end
  end
end
