# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kylRxFitSizeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kylRxFitSizeDemo
  pod 'WCDB.swift'
  pod 'RxSwift' ,    '~> 4.4'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'SnapKit'

  target 'kylRxFitSizeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kylRxFitSizeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
