# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kylRealmSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   
  # Pods for kylRealmSwiftDemo
      # Persistence
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  # Model
  pod 'ObjectMapper'
  
  target 'kylRealmSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kylRealmSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
